
package logregis;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lenovo
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    //String name;
    public homepage() {
        initComponents();
        regis reg = new regis();
        labelnama.setText(login.usr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cariResto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addInfo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rekomend = new javax.swing.JButton();
        cariMakan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kuliner Wong Cirebon");

        cariResto.setText("Cari");
        cariResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariRestoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("KUWOCI");

        jLabel2.setText("Cari menu kuliner di Cirebon? Klik disini!");

        jLabel5.setText("Punya usaha kuliner atau saran pusat kuliner di Cirebon?");

        addInfo.setText("Add Info");
        addInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInfoActionPerformed(evt);
            }
        });

        jLabel6.setText("Rekomendasi menu kuliner Cirebon");

        rekomend.setText("Rekomendasi");
        rekomend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekomendActionPerformed(evt);
            }
        });

        cariMakan.setText("Cari");
        cariMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariMakanActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari pusat kuliner di Cirebon? Klik disini!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rekomend)
                                    .addComponent(jLabel5)
                                    .addComponent(addInfo))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(cariMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariResto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 183, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(cariResto)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(cariMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(rekomend)
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addInfo)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInfoActionPerformed
        // TODO add your handling code here:
        tambahInfo tbh = new tambahInfo();
        tbh.setVisible(true);
        tbh.pack();
        tbh.setLocationRelativeTo(null);
        tbh.setDefaultCloseOperation(regis.EXIT_ON_CLOSE);
    }//GEN-LAST:event_addInfoActionPerformed

    private void rekomendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekomendActionPerformed
        // TODO add your handling code here:
        reccomend rk = new reccomend();
        rk.setVisible(true);
        rk.pack();
        rk.setLocationRelativeTo(null);
        rk.setDefaultCloseOperation(regis.EXIT_ON_CLOSE);
    }//GEN-LAST:event_rekomendActionPerformed

    private void cariRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariRestoActionPerformed
        // TODO add your handling code here:
        tampilresto tf = new tampilresto();
        tf.setVisible(true);
        tf.pack();
        tf.setLocationRelativeTo(null);
        tf.setDefaultCloseOperation(regis.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_cariRestoActionPerformed

    private void cariMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariMakanActionPerformed
        // TODO add your handling code here:
        //String key = null; System.out.println("Keyword pencarian:" + key);
        //key = fieldfood.getText();

        tampilfood tf = new tampilfood();
        tf.setVisible(true);
        tf.pack();
        tf.setLocationRelativeTo(null);
        tf.setDefaultCloseOperation(regis.EXIT_ON_CLOSE);

        /*if(key!= ""){
            //pencarianMakanan(key);
        }else{
            System.out.println("Keyword tidak ditemukan");
        }*/
    }//GEN-LAST:event_cariMakanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }
    
    /*private void pencarianMakanan(String key){
        Connection dbconn = Logregis.koneksiDB();
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("nama");
        tbl.addColumn("harga");
        tbl.addColumn("restoran");
        tbl.addColumn("deskripsi");
        if(dbconn!=null){
            try{
                Statement st = dbconn.createStatement();
                ResultSet rs = st.executeQuery("SELECT * from menukwc WHERE nama LIKE '%"+key+"%' OR harga LIKE '%"+key+"%' OR restoran LIKE '%"+key+"%'");
                
            }catch (Exception ex){
                
            }
        }
        //int row = tabel
        /*Object[] kolom = {"nama", "harga", "restoran", "deskripsi"};
        DefaultTableModel tabModel = new DefaultTableModel(null, kolom);
        if(dbconn!=null){
            if(key.isEmpty()){
                JOptionPane.showMessageDialog(this, "Silahkan isi keyword pencarian","Error", JOptionPane.ERROR_MESSAGE);
            }else{
                try {
                    Statement st = dbconn.createStatement();
                    ResultSet f_search = st.executeQuery("SELECT * from menukwc WHERE nama LIKE '%"+key+"%' OR harga LIKE '%"+key+"%' OR restoran LIKE '%"+key+"%'"); 
                    while(f_search.next()){
                        Object[] data={
                            f_search.getString("nama");
                            f_search.getString("harga");
                            f_search.getString("restoran");
                            f_search.getString("deskripsi");
                        };
                    }
                }catch(Exception ex){
                    System.err.println(ex.getMessage());
                }
            }*/
        

     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInfo;
    private javax.swing.JButton cariMakan;
    private javax.swing.JButton cariResto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelnama;
    private javax.swing.JButton rekomend;
    // End of variables declaration//GEN-END:variables
}
